@host = http://localhost:3000/api/auth

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTcwMDc1Njc5OCwiZXhwIjoxNzAwNzYwMzk4fQ.62uSyDN0EFmidLdj90RI1-t2DEOBnC4Em1RUg4ShNG0
### 회원가입
POST {{host}}/signup
Content-Type: application/json

{
    "name": "example7",
    "email": "example7@naver.com",
    "password": "example7",
    "passwordConfirm": "example7",
    "gender": "women",
    "birthday": "1999-12-13"
}

### 로그인

POST {{host}}/signin
Content-Type: application/json

{
    "email": "example3@naver.com",
    "password": "example3"
}

### 로그아웃
DELETE {{host}}/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}
